---
- hosts: gateway.local
  connection: ssh
  become: yes
  gather_facts: true

  tasks:
    - name: Firewall setup
      shell:
        cmd: |
          firewall-cmd --reset-to-defaults
          firewall-cmd --permanent --zone=external --add-masquerade
          firewall-cmd --permanent --zone=external --add-interface=en0dmz
          firewall-cmd --permanent --zone=external --add-source=192.168.1.0/24
          firewall-cmd --permanent --zone=home --add-interface=en1lan
          firewall-cmd --permanent --zone=home --add-source=192.168.86.0/24
          firewall-cmd --permanent --zone=home --set-target ACCEPT
          firewall-cmd --permanent --zone=home --add-service ssh
          firewall-cmd --permanent --zone=home --add-service dns
          firewall-cmd --permanent --zone=home --add-service mdns
          firewall-cmd --permanent --zone=home --add-service dhcp
          firewall-cmd --permanent --zone=home --add-service dhcpv6
          firewall-cmd --permanent --zone=home --add-service dhcpv6-client
          firewall-cmd --reload
          systemctl enable --now firewalld

    - name: DHCP setup
      file:
        content: |
          server6:
            listen:
              - "[ff02::1:2%en1lan]"
              - "[ff05::1:3%en1lan]"
            plugins:
              - server_id: LL c0:74:2b:fc:72:da
          server4:
            listen:
              - "%en1lan"
            plugins:
              - lease_time: 3600s
              - server_id: 192.168.86.1
              - dns: 1.1.1.1 8.8.8.8
              - netmask: 255.255.255.0
              - range: leases.txt 192.168.86.100 192.168.86.200 3600s
        dest: /etc/coredhcp/config.yml
        mode: 0644
