---
- hosts: localhost
  connection: local
  become: yes  # use sudo
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    environment:
      USER: lookup('env', 'USER')
      PW: lookup('env', 'PW')

    - name: Ensure the mounted filesystem exists
      ansible.builtin.stat:
        path: "{{ mount_point }}"
      register: mount_check

    - name: Fail if mount point does not exist
      ansible.builtin.fail:
        msg: "FS is not mounted at {{ mount_point }}."
      when: not mount_check.stat.exists

    - name: Set the hostname, blindly
      ansible.builtin.copy:
        mode: 0644
        directory_mode: 0755
        owner: root
        group: root
        content: "gateway"
        dest: "{{ mount_point }}/etc/hostname"

    - name: Turn on ssh service
      ansible.builtin.command:
        cmd: "chroot {{ mount_point }} systemctl enable ssh.service"

    - name: create user ('steve' for me...)
      ansible.builtin.command:
        cmd: "chroot {{ mount_point }} bash -c 'fgrep steve /etc/passwd || useradd -G adm,sudo,users -m -s /bin/bash steve'"

    - name: set a password for user
      ansible.builtin.shell:
        cmd: >
          echo -e "temp\ntemp\n" | chroot {{ mount_point }} passwd steve"

    - name: get UID for new user (else Ansible uses value from this host machine)
      shell:
        cmd: "grep steve {{ mount_point }}/etc/passwd | cut -d':' -f3"
      register: user_uid

    - name: get GID
      shell:
        cmd: "grep steve {{ mount_point }}/etc/passwd | cut -d':' -f4"
      register: user_gid

    - name: Make .ssh dir for user
      ansible.builtin.file:
        owner: "{{ user_uid.stdout }}"
        group: "{{ user_gid.stdout }}"
        mode: 0700
        state: directory
        path: "{{ mount_point }}/home/{{ ansible_env.USER }}/.ssh"

    - name: Copy ssh key authorization for USER
      ansible.builtin.copy:
        mode: 0600
        owner: "{{ user_uid.stdout }}"
        group: "{{ user_gid.stdout }}"
        source: "/home/{{ ansible_env.USER }}/.ssh/id_rsa.pub"
        dest: "{{ mount_point }}/home/{{ ansible_env.USER }}/.ssh/authorized_keys"

    - name: USER to password-free sudo (for post-boot Ansible operations)
      shell:
        cmd: "echo 'steve ALL = (ALL) NOPASSWD: ALL' > {{ mount_point }}/etc/sudoers.d/steve"

    - name: Rename network interface 1
      file:
        mode: 0600
        destination: /etc/udev/rules.d/90-naming-netifs.rules
        content: >
          SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="c0:74:2b:fc:72:da", NAME="en0dmz"
          SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="c0:74:2b:fc:72:db", NAME="en1lan"

    - name: Update apt
      ansible.builtin.command:
        cmd: "chroot {{ mount_point }} apt update"

    - name: Install netplan
      ansible.builtin.command:
        cmd: "chroot {{ mount_point }} apt install -y netplan.io"

    - name: Static netplan configuration
      ansible.builtin.copy:
        mode: 0600
        directory_mode: 0755
        owner: root
        group: root
        content: |
          network:
            version: 2
            ethernets:
              en0dmz:
                match:
                  macaddress: "c0:74:2b:fc:72:da"
                dhcp4: yes
                routes:
                  - to: 192.168.86.0/24
                    via: 192.168.86.1
                    metric: 100
                    on-link: false
              en1lan:
                match:
                  macaddress: "c0:74:2b:fc:72:db"
                addresses: [192.168.86.1/24]
                nameservers:
                  addresses: [1.1.1.1, 8.8.8.8]
                routes:
                  - to: default
                    via: 192.168.86.1
                    metric: 100
                    on-link: true
        dest: "{{ mount_point }}/etc/netplan/four-oh-four-gateway.yaml"
